#!/usr/bin/python
import rospy
import yaml
#import watchdog.monitors

from watchdog.monitors import MonitorType
from watchdog.actions import ActionType

print "Actions available:"
print
for act in MonitorType.registry.values():
    print "- type: ", act.name
    print "  descripton: ", act.description
    print "  configuration fields:"
    for f in act.config_keys:
        print "    - ", f[0], " : ",  f[1]
    print
print
print "Actions available:"
print
for act in ActionType.registry.values():
    print "- type: ", act.name
    print "  descripton: ", act.description
    print "  configuration fields:"
    for f in act.config_keys:
        print "    - ", f[0], " : ",  f[1]
    print
raw_input()