#!/usr/bin/python
import rospy
import yaml
from watchdog_node import Watchdog
import sys
from threading import Thread

rospy.init_node("watchdog")
try:
    config_file =  rospy.get_param("~config")
except:
    rospy.logerr("Could not get config parameter. Make sure to supply a YAML "
                 "configuration file.")
    sys.exit(1)
    
with open(config_file, "r") as f:
    config = yaml.load(f.read())

watchdogs =  {}
for c in config:
    rospy.loginfo("Creating '{}' watchdog".format(c['name']))
    watchdogs[c['name']] = w = Watchdog(c)
    w.run()

rospy.loginfo("Watchdogs started")
rospy.spin()
w.shutdown()
